# ROCKS.NVIM

# non nvim rocks
# TODO put this part of the toml in a seperate file in the root directory
[rocks]
microlight = "1.0"
tinytoml = "0.0.4"
catppuccin = "0.1.0"
inifile = "1.1"
warna = "0.3.5"
luafilesystem = "1.8.0"

# CONFIG
[config]
colorscheme = "sweetie"

[config.options]
autochdir = true
background = "dark" # TODO create keybind and lua script to control this
clipboard = "unnamedplus"
cmdheight = 0
laststatus = 1
number = true
numberwidth = 3
relativenumber = true
scrolloff = 10000
showtabline = 0
signcolumn = "no"
termguicolors = true
smoothscroll = true
winborder = "rounded"
visualbell = true

# PLUGINS
[plugins]
"dracula.nvim" = "scm"
#"feed.nvim" = "2.19.0"
"lazygit.nvim" = "scm"
"lsp-status.nvim" = "scm"
"mini.nvim" = "0.17.0"
"oil.nvim" = "2.15.0"
"plenary.nvim" = "scm"
"render-markdown.nvim" = "8.10.0"
"rocks-config.nvim" = "3.1.2"
"rocks-git.nvim" = "2.5.7"
"rocks-treesitter.nvim" = "1.3.1"
"rocks.nvim" = "2.46.1"
"smart-splits.nvim" = "2.0.5"
"sweetie.nvim" = "3.2.0"
"unnest.nvim" = "0.1.1"
nvim-lspconfig = "2.5.0"
tree-sitter-gdscript = "0.0.45"
tree-sitter-javascript = "0.0.41"
tree-sitter-lua = "0.0.36"
tree-sitter-markdown = "0.0.45"
tree-sitter-toml = "0.0.31"
"leap.nvim" = "scm"
neorg = "9.3.0"
"diffview.nvim" = "scm"

[plugins.tv]
git = "alexpasmantier/tv.nvim"
rev = "176c97ce7e18b1a5acd473b320d03773901a8f75"

[plugins.snipe]
git = "leath-dub/snipe.nvim"
rev = "d2d196c335919767803f905d573ce66340e33ee6"

[plugins.debugprint]
git = "andrewferrier/debugprint.nvim"
rev = "v6.3.0"

[plugins.eldritch]
git = "eldritch-theme/eldritch.nvim"
rev = "cddd745d4bd317a5c142708def49fd466fd87fc6"

[plugins.oceanic-next]
git = "mhartington/oceanic-next"
rev = "09833f72d5ba23de2e8bcae18f479f326f5f677a"

[plugins.vim-moonfly-colors]
git = "bluz71/vim-moonfly-colors"
rev = "1ad5a8d40176a8749f0c77b8875225d9d299a438"

[plugins.neomodern]
git = "casedami/neomodern.nvim"
rev = "v1.0.4"

[plugins.srcery-vim]
git = "srcery-colors/srcery-vim"
rev = "v2.1.0"

[plugins.seoul256]
git = "junegunn/seoul256.vim"
rev = "d9a91d8d4e153274e1ecc0ceb05c37f0d0de84d7"
