# ROCKS.NVIM

[rocks]
microlight = "1.0"
tinytoml = "1.0.0"
catppuccin = "0.1.0"
inifile = "1.1"
warna = "0.3.5"
luafilesystem = "1.8.0"

# CONFIG
[config]
colorscheme = "challenger_deep"

[config.options]
autochdir = true
background = "dark" # TODO create keybind and lua script to control this
clipboard = "unnamedplus"
cmdheight = 0
laststatus = 1
number = true
numberwidth = 3
relativenumber = true
scrolloff = 10000
showtabline = 0
signcolumn = "no"
termguicolors = true
smoothscroll = true
winborder = "rounded"
visualbell = true

# PLUGINS
[plugins]
"dracula.nvim" = "scm"
#"feed.nvim" = "2.19.0"
"lazygit.nvim" = "scm"
"lsp-status.nvim" = "scm"
"mini.nvim" = "0.17.0"
"oil.nvim" = "2.15.0"
"plenary.nvim" = "scm"
"render-markdown.nvim" = { version = "8.11.0", ft = "md" }
"rocks-config.nvim" = "3.1.2"
"rocks-git.nvim" = "2.5.8"
"rocks-treesitter.nvim" = "1.3.1"
"rocks.nvim" = "2.47.2"
"smart-splits.nvim" = "2.0.5"
"sweetie.nvim" = "3.2.0"
"unnest.nvim" = "0.1.1"
nvim-lspconfig = "2.5.0"
tree-sitter-lua = "0.0.42"
tree-sitter-javascript = "0.0.41"
tree-sitter-toml = "0.0.31"
neorg = { version = "9.3.0", ft = "norg" }
"rocks-lazy.nvim" = "1.2.2"
"lush.nvim" = "scm"
"cybu.nvim" = "1.0"
"snipe.nvim" = "scm"
# "diffview.nvim" = "scm" -- use with gitu?

# GIT PLUGINS ##############################################################
[plugins.tv]
git = "alexpasmantier/tv.nvim"
rev = "176c97ce7e18b1a5acd473b320d03773901a8f75"

[plugins.nvim-chainsaw]
git = "chrisgrieser/nvim-chainsaw"
rev = "8962d33ad432568a47bfd79faf098130a28498c4"

[plugins.opencode]
git = "NickvanDyke/opencode.nvim"
rev = "7ae1f9a969b9e6d090673227a0ad1db2e808216d"

# GIT COLORS ###############################################################
[plugins.eldritch]
git = "eldritch-theme/eldritch.nvim"
rev = "cddd745d4bd317a5c142708def49fd466fd87fc6"

[plugins.bluloco]
git = "uloco/bluloco.nvim"
rev = "v1.4.0"

[plugins.oceanic-next]
git = "mhartington/oceanic-next"
rev = "09833f72d5ba23de2e8bcae18f479f326f5f677a"

[plugins.vim-moonfly-colors]
git = "bluz71/vim-moonfly-colors"
rev = "1ad5a8d40176a8749f0c77b8875225d9d299a438"

[plugins.neomodern]
git = "casedami/neomodern.nvim"
rev = "v1.0.4"

[plugins.srcery-vim]
git = "srcery-colors/srcery-vim"
rev = "v2.1.0"

[plugins.challenger-deep]
git = "challenger-deep-theme/vim"
rev = "e3d5b7d9711c7ebbf12c63c2345116985656da0d"

[plugins.boo-colorscheme-nvim]
git = "rockerboo/boo-colorscheme-nvim"
rev = "0.5.2"

[plugins.mfd]
git = "kungfusheep/mfd.nvim"

[plugins.vim-256noir]
git = "andreasvc/vim-256noir"

[plugins.seoul256]
git = "junegunn/seoul256.vim"

[plugins.space-vim-dark]
git = "liuchengxu/space-vim-dark"

[plugins.vim-dogrun]
git = "wadackel/vim-dogrun"

[plugins.yorumi]
git = "yorumicolors/yorumi.nvim"

[plugins.noirblaze-vim]
git = "n1ghtmare/noirblaze-vim"
rev = "03132e01915d261ce5a8812ec633ff63d84718a1"
