# Bookmarks

[github]
name = "GitHub"
url = "https://github.com/aquarockslug"

[youtube]
name = "YouTube"
url = "https://youtube.com"

[wikipedia]
name = "Wikipedia"
url = "https://wikipedia.org"

[neovim]
name = "Neovim"
url = "https://neovim.io"

[luarocks]
name = "Luarocks"
url = "https://luarocks.org"

[aur]
name = "Arch User Repository"
url = "https://aur.archlinux.org/"

[arch_wiki]
name = "Arch Wiki"
url = "https://wiki.archlinux.org"
