[general]
always_show_help.enabled = false
mouse_support = true
confirm_discard = "line"
collapsed_sections = ["branch_status", "untracked", "unstaged_changes", "recent_commits", "stashes"]

[style]
section_header = { fg = "#bbbac1", mods = "ITALIC|BOLD" }
file_header = { fg = "#cc93b8" }
syntax_highlight.keyword = { fg = "#cc93b8" }
hash = { fg = "#cc93b8" }
tag = { fg = "#cc93b8" }
cursor = { symbol = "▌", fg = "#bbbac1" }
selection_bar = { symbol = "▌", fg = "#abbceb", mods = "DIM" }
selection_line = { mods = "BOLD" }
selection_area = {}
