[general]
always_show_help.enabled = true
mouse_support = true
confirm_discard = "line"

[style]
section_header = { fg = "#92d3c5", mods = "ITALIC|BOLD" }
file_header = { fg = "#b094e2" }
syntax_highlight.keyword = { fg = "#b094e2" }
hash = { fg = "#b094e2" }
tag = { fg = "#b094e2" }
cursor = { symbol = "▌", fg = "#92d3c5" }
selection_bar = { symbol = "▌", fg = "#d3d7de", mods = "DIM" }
selection_line = { mods = "BOLD" }
selection_area = {}
