# general
background = '#080808'
border_fg = '#AE81ff'
text_fg = '#AE81ff'
dimmed_text_fg = '#737994'
# input
input_text_fg = '#AE81ff'
result_count_fg = '#AE81ff'
# results
result_name_fg = '#AE81ff'
result_line_number_fg = '#e5c890'
result_value_fg = '#AE81ff'
selection_fg = '#AE81FF'
selection_bg = '#080808'
match_fg = '#BDBDBD'
# preview
preview_title_fg = '#AE81ff'
# modes
channel_mode_fg = '#303446'
channel_mode_bg = '#AE81ff'
remote_control_mode_fg = '#303446'
remote_control_mode_bg = '#a6d189'
