[ui]
ui_scale = 99
orientation = "landscape"
theme = "ansi"

[ui.input_bar]
prompt = " ó°ˆ¿_"
border_type = "thick"

[ui.results_panel]
border_type = "thick"

[ui.preview_panel]
border_type = "thick"

[ui.theme_overrides]
dimmed_text_fg = "#d3d7de"
remote_control_mode_bg = "#b094e2"
preview_title_fg = "#92d3c5"
result_count_fg = "#92d3c5"
result_line_number_fg = "#b094e2"
match_fg = "#d3d7de"
text_fg = "#92d3c5"
background = "#2a2a3a"
channel_mode_fg = "#2a2a3a"
channel_mode_bg = "#92d3c5"
selection_fg = "#92d3c5"
remote_control_mode_fg = "#2a2a3a"
input_text_fg = "#92d3c5"
border_fg = "#92d3c5"
result_value_fg = "#92d3c5"
selection_bg = "#2a2a3a"
result_name_fg = "#92d3c5"

[shell_integration]
fallback_channel = "files"

[shell_integration.keybindings]
smart_autocomplete = "ctrl-s"
command_history = "ctrl-h"

