[ui]
ui_scale = 99
orientation = "landscape"
theme = "ansi"

[ui.results_panel]
border_type = "thick"

[ui.theme_overrides]
remote_control_mode_bg = "#cf87e8"
channel_mode_fg = "#080808"
remote_control_mode_fg = "#080808"
border_fg = "#ae81ff"
text_fg = "#ae81ff"
result_value_fg = "#ae81ff"
result_name_fg = "#ae81ff"
input_text_fg = "#ae81ff"
dimmed_text_fg = "#bdbdbd"
preview_title_fg = "#ae81ff"
match_fg = "#bdbdbd"
background = "#080808"
selection_fg = "#ae81ff"
result_line_number_fg = "#cf87e8"
channel_mode_bg = "#ae81ff"
selection_bg = "#080808"
result_count_fg = "#ae81ff"

[ui.input_bar]
border_type = "thick"
prompt = " ó°ˆ¿_"

[ui.preview_panel]
border_type = "thick"

[shell_integration]
fallback_channel = "files"

[shell_integration.keybindings]
smart_autocomplete = "ctrl-s"
command_history = "ctrl-h"

