[ui]
ui_scale = 99
orientation = "landscape"
theme = "ansi"

[ui.results_panel]
border_type = "thick"

[ui.theme_overrides]
selection_fg = "#bbbac1"
selection_bg = "#171719"
preview_title_fg = "#bbbac1"
result_line_number_fg = "#cc93b8"
remote_control_mode_fg = "#171719"
background = "#171719"
result_value_fg = "#bbbac1"
dimmed_text_fg = "#abbceb"
text_fg = "#bbbac1"
channel_mode_fg = "#171719"
remote_control_mode_bg = "#cc93b8"
channel_mode_bg = "#bbbac1"
result_name_fg = "#bbbac1"
border_fg = "#bbbac1"
match_fg = "#abbceb"
result_count_fg = "#bbbac1"
input_text_fg = "#bbbac1"

[ui.preview_panel]
border_type = "thick"

[ui.input_bar]
border_type = "thick"
prompt = " ó°ˆ¿_"

[shell_integration]
fallback_channel = "files"

[shell_integration.keybindings]
command_history = "ctrl-h"
smart_autocomplete = "ctrl-s"

