[ui]
ui_scale = 99
orientation = "landscape"
theme = "ansi"

[ui.preview_panel]
border_type = "thick"

[ui.input_bar]
prompt = " ó°ˆ¿_"
border_type = "thick"

[ui.results_panel]
border_type = "thick"

[ui.theme_overrides]
result_line_number_fg = "#f99157"
text_fg = "#5fb3b3"
preview_title_fg = "#5fb3b3"
selection_fg = "#5fb3b3"
dimmed_text_fg = "#d8dee9"
remote_control_mode_bg = "#f99157"
remote_control_mode_fg = "#1b2b34"
result_count_fg = "#5fb3b3"
result_name_fg = "#5fb3b3"
result_value_fg = "#5fb3b3"
selection_bg = "#1b2b34"
background = "#1b2b34"
channel_mode_fg = "#1b2b34"
border_fg = "#5fb3b3"
channel_mode_bg = "#5fb3b3"
input_text_fg = "#5fb3b3"
match_fg = "#d8dee9"

[shell_integration]
fallback_channel = "files"

[shell_integration.keybindings]
command_history = "ctrl-h"
smart_autocomplete = "ctrl-s"

